const constants = {
    placeholders: [
        "What comes to your mind today?",
        "Today I feel like playing...",
        "What do you want to play?",
        "Type something magical!",
        "Your imagination starts here...",
        "Share your next big idea!",
        "Feeling adventurous? Type away!",
        "What's your next move?",
        "Unleash your creativity!",
        "Let's make something awesome!",
        "Dare to dream big?",
        "Today is a great day to begin.",
        "Ready, set, type!",
        "Insert brilliance here...",
        "What's cooking in your mind?",
        "Type like nobody's watching!",
        "It's your time to shine!",
        "Ready to make waves?",
        "What inspires you today?",
        "Say something cool!",
        "Time for your next masterpiece!",
        "Channel your inner genius!",
        "Brainstorming? Let's go!",
        "What's on your mind, champion?",
        "Feeling lucky? Start typing!",
        "Your story begins here...",
        "Go ahead, surprise yourself!",
        "No pressure, just awesomeness!",
        "How did that song started? Look for it!",
        "Let's create some magic!"
    ],
};

export default constants;
